# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ ... }:

{

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  systemd.tmpfiles.rules = [
    "d /mnt 0755 root root -"
    "d /mnt/usb 0755 root root -"
  ];

  boot.initrd.luks.devices."root".device = "/dev/disk/by-partlabel/cryptroot";
  boot.initrd.luks.devices."swap" = {
    device = "/dev/disk/by-partlabel/cryptswap";
    preLVM = true;
    allowDiscards = true;
  };

  fileSystems."/" = { 
    device = "/dev/mapper/root";
    fsType = "ext4";
  };

  
  fileSystems."/boot" = { 
    device = "/dev/disk/by-label/BOOT";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [{ 
    device = "/dev/mapper/swap";
  }];
  

}
